export const COUNTRIES = {
  AF: "Afghanistan",
  AX: "Åland Islands",
  AL: "Albania",
  DZ: "Algeria",
  AS: "American Samoa",
  AD: "AndorrA",
  AO: "Angola",
  AI: "Anguilla",
  AQ: "Antarctica",
  AG: "Antigua and Barbuda",
  AR: "Argentina",
  AM: "Armenia",
  AW: "Aruba",
  AU: "Australia",
  AT: "Austria",
  AZ: "Azerbaijan",
  BS: "Bahamas",
  BH: "Bahrain",
  BD: "Bangladesh",
  BE: "Belgium",
  BZ: "Belize",
  BJ: "Benin",
  BM: "Bermuda",
  BT: "Bhutan",
  BO: "Bolivia",
  BA: "Bosnia and Herzegovina",
  BW: "Botswana",
  BV: "Bouvet Island",
  BR: "Brazil",
  IO: "British Indian Ocean Territory",
  BN: "Brunei Darussalam",
  BG: "Bulgaria",
  BF: "Burkina Faso",
  BI: "Burundi",
  KH: "Cambodia",
  CM: "Cameroon",
  CA: "Canada",
  CV: "Cape Verde",
  KY: "Cayman Islands",
  CF: "Central African Republic",
  TD: "Chad",
  CL: "Chile",
  CN: "China",
  CX: "Christmas Island",
  CC: "Cocos (Keeling) Islands",
  CO: "Colombia",
  KM: "Comoros",
  CG: "Congo",
  CD: "Congo, The Democratic Republic of the",
  CK: "Cook Islands",
  CR: "Costa Rica",
  CI: "Cote D Ivoire",
  HR: "Croatia",
  CU: "Cuba",
  CY: "Cyprus",
  CZ: "Czech Republic",
  DK: "Denmark",
  DJ: "Djibouti",
  DM: "Dominica",
  DO: "Dominican Republic",
  EC: "Ecuador",
  EG: "Egypt",
  SV: "El Salvador",
  GQ: "Equatorial Guinea",
  ER: "Eritrea",
  EE: "Estonia",
  ET: "Ethiopia",
  FK: "Falkland Islands (Malvinas)",
  FO: "Faroe Islands",
  FJ: "Fiji",
  FI: "Finland",
  FR: "France",
  GF: "French Guiana",
  PF: "French Polynesia",
  TF: "French Southern Territories",
  GA: "Gabon",
  GM: "Gambia",
  GE: "Georgia",
  DE: "Germany",
  GH: "Ghana",
  GI: "Gibraltar",
  GR: "Greece",
  GL: "Greenland",
  GD: "Grenada",
  GP: "Guadeloupe",
  GU: "Guam",
  GT: "Guatemala",
  GG: "Guernsey",
  GN: "Guinea",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HT: "Haiti",
  HM: "Heard Island and Mcdonald Islands",
  VA: "Holy See (Vatican City State)",
  HN: "Honduras",
  HK: "Hong Kong",
  HU: "Hungary",
  IS: "Iceland",
  IN: "India",
  ID: "Indonesia",
  IR: "Iran, Islamic Republic Of",
  IQ: "Iraq",
  IE: "Ireland",
  IM: "Isle of Man",
  IL: "Israel",
  IT: "Italy",
  JM: "Jamaica",
  JP: "Japan",
  JE: "Jersey",
  JO: "Jordan",
  KZ: "Kazakhstan",
  KE: "Kenya",
  KI: "Kiribati",
  KP: "Korea, Democratic People Republic of",
  KR: "Korea, Republic of",
  KW: "Kuwait",
  KG: "Kyrgyzstan",
  LA: "Lao People Democratic Republic",
  LV: "Latvia",
  LB: "Lebanon",
  LS: "Lesotho",
  LR: "Liberia",
  LY: "Libyan Arab Jamahiriya",
  LI: "Liechtenstein",
  LT: "Lithuania",
  LU: "Luxembourg",
  MO: "Macao",
  MK: "Macedonia, The Former Yugoslav Republic of",
  MG: "Madagascar",
  MW: "Malawi",
  MY: "Malaysia",
  MV: "Maldives",
  ML: "Mali",
  MT: "Malta",
  MH: "Marshall Islands",
  MQ: "Martinique",
  MR: "Mauritania",
  MU: "Mauritius",
  YT: "Mayotte",
  MX: "Mexico",
  FM: "Micronesia, Federated States of",
  MD: "Moldova, Republic of",
  MC: "Monaco",
  MN: "Mongolia",
  MS: "Montserrat",
  MA: "Morocco",
  MZ: "Mozambique",
  MM: "Myanmar",
  NA: "Namibia",
  NR: "Nauru",
  NP: "Nepal",
  NL: "Netherlands",
  AN: "Netherlands Antilles",
  NC: "New Caledonia",
  NZ: "New Zealand",
  NI: "Nicaragua",
  NE: "Niger",
  NG: "Nigeria",
  NU: "Niue",
  NF: "Norfolk Island",
  MP: "Northern Mariana Islands",
  NO: "Norway",
  OM: "Oman",
  PK: "Pakistan",
  PW: "Palau",
  PS: "Palestinian Territory, Occupied",
  PA: "Panama",
  PG: "Papua New Guinea",
  PY: "Paraguay",
  PE: "Peru",
  PH: "Philippines",
  PN: "Pitcairn",
  PL: "Poland",
  PT: "Portugal",
  PR: "Puerto Rico",
  QA: "Qatar",
  RE: "Reunion",
  RO: "Romania",
  RU: "Russian Federation",
  RW: "RWANDA",
  SH: "Saint Helena",
  KN: "Saint Kitts and Nevis",
  LC: "Saint Lucia",
  PM: "Saint Pierre and Miquelon",
  VC: "Saint Vincent and the Grenadines",
  WS: "Samoa",
  SM: "San Marino",
  ST: "Sao Tome and Principe",
  SA: "Saudi Arabia",
  SN: "Senegal",
  CS: "Serbia and Montenegro",
  SC: "Seychelles",
  SL: "Sierra Leone",
  SG: "Singapore",
  SK: "Slovakia",
  SI: "Slovenia",
  SB: "Solomon Islands",
  SO: "Somalia",
  ZA: "South Africa",
  GS: "South Georgia and the South Sandwich Islands",
  ES: "Spain",
  LK: "Sri Lanka",
  SD: "Sudan",
  SR: "Suriname",
  SJ: "Svalbard and Jan Mayen",
  SZ: "Swaziland",
  SE: "Sweden",
  CH: "Switzerland",
  SY: "Syrian Arab Republic",
  TW: "Taiwan, Province of China",
  TJ: "Tajikistan",
  TZ: "Tanzania, United Republic of",
  TH: "Thailand",
  TL: "Timor-Leste",
  TG: "Togo",
  TK: "Tokelau",
  TO: "Tonga",
  TT: "Trinidad and Tobago",
  TN: "Tunisia",
  TR: "Turkey",
  TM: "Turkmenistan",
  TC: "Turks and Caicos Islands",
  TV: "Tuvalu",
  UG: "Uganda",
  UA: "Ukraine",
  AE: "United Arab Emirates",
  GB: "United Kingdom",
  US: "United States",
  UM: "United States Minor Outlying Islands",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VU: "Vanuatu",
  VE: "Venezuela",
  VN: "Viet Nam",
  VG: "Virgin Islands, British",
  VI: "Virgin Islands, U.S.",
  WF: "Wallis and Futuna",
  EH: "Western Sahara",
  YE: "Yemen",
  ZM: "Zambia",
  ZW: "Zimbabwe",
} as const;

const ContinentCodes = {
  AD: "EU",
  AE: "AS",
  AF: "AS",
  AG: "NA",
  AI: "NA",
  AL: "EU",
  AM: "AS",
  AO: "AF",
  AQ: "AN",
  AR: "SA",
  AS: "OC",
  AT: "EU",
  AU: "OC",
  AW: "NA",
  AX: "EU",
  AZ: "AS",
  BA: "EU",
  BB: "NA",
  BD: "AS",
  BE: "EU",
  BF: "AF",
  BG: "EU",
  BH: "AS",
  BI: "AF",
  BJ: "AF",
  BL: "NA",
  BM: "NA",
  BN: "AS",
  BO: "SA",
  BQ: "NA",
  BR: "SA",
  BS: "NA",
  BT: "AS",
  BV: "AN",
  BW: "AF",
  BY: "EU",
  BZ: "NA",
  CA: "NA",
  CC: "AS",
  CD: "AF",
  CF: "AF",
  CG: "AF",
  CH: "EU",
  CI: "AF",
  CK: "OC",
  CL: "SA",
  CM: "AF",
  CN: "AS",
  CO: "SA",
  CR: "NA",
  CU: "NA",
  CV: "AF",
  CW: "NA",
  CX: "AS",
  CY: "EU",
  CZ: "EU",
  DE: "EU",
  DJ: "AF",
  DK: "EU",
  DM: "NA",
  DO: "NA",
  DZ: "AF",
  EC: "SA",
  EE: "EU",
  EG: "AF",
  EH: "AF",
  ER: "AF",
  ES: "EU",
  ET: "AF",
  FI: "EU",
  FJ: "OC",
  FK: "SA",
  FM: "OC",
  FO: "EU",
  FR: "EU",
  GA: "AF",
  GB: "EU",
  GD: "NA",
  GE: "AS",
  GF: "SA",
  GG: "EU",
  GH: "AF",
  GI: "EU",
  GL: "NA",
  GM: "AF",
  GN: "AF",
  GP: "NA",
  GQ: "AF",
  GR: "EU",
  GS: "AN",
  GT: "NA",
  GU: "OC",
  GW: "AF",
  GY: "SA",
  HK: "AS",
  HM: "AN",
  HN: "NA",
  HR: "EU",
  HT: "NA",
  HU: "EU",
  ID: "AS",
  IE: "EU",
  IL: "AS",
  IM: "EU",
  IN: "AS",
  IO: "AS",
  IQ: "AS",
  IR: "AS",
  IS: "EU",
  IT: "EU",
  JE: "EU",
  JM: "NA",
  JO: "AS",
  JP: "AS",
  KE: "AF",
  KG: "AS",
  KH: "AS",
  KI: "OC",
  KM: "AF",
  KN: "NA",
  KP: "AS",
  KR: "AS",
  KW: "AS",
  KY: "NA",
  KZ: "AS",
  LA: "AS",
  LB: "AS",
  LC: "NA",
  LI: "EU",
  LK: "AS",
  LR: "AF",
  LS: "AF",
  LT: "EU",
  LU: "EU",
  LV: "EU",
  LY: "AF",
  MA: "AF",
  MC: "EU",
  MD: "EU",
  ME: "EU",
  MF: "NA",
  MG: "AF",
  MH: "OC",
  MK: "EU",
  ML: "AF",
  MM: "AS",
  MN: "AS",
  MO: "AS",
  MP: "OC",
  MQ: "NA",
  MR: "AF",
  MS: "NA",
  MT: "EU",
  MU: "AF",
  MV: "AS",
  MW: "AF",
  MX: "NA",
  MY: "AS",
  MZ: "AF",
  NA: "AF",
  NC: "OC",
  NE: "AF",
  NF: "OC",
  NG: "AF",
  NI: "NA",
  NL: "EU",
  NO: "EU",
  NP: "AS",
  NR: "OC",
  NU: "OC",
  NZ: "OC",
  OM: "AS",
  PA: "NA",
  PE: "SA",
  PF: "OC",
  PG: "OC",
  PH: "AS",
  PK: "AS",
  PL: "EU",
  PM: "NA",
  PN: "OC",
  PR: "NA",
  PS: "AS",
  PT: "EU",
  PW: "OC",
  PY: "SA",
  QA: "AS",
  RE: "AF",
  RO: "EU",
  RS: "EU",
  RU: "EU",
  RW: "AF",
  SA: "AS",
  SB: "OC",
  SC: "AF",
  SD: "AF",
  SE: "EU",
  SG: "AS",
  SH: "AF",
  SI: "EU",
  SJ: "EU",
  SK: "EU",
  SL: "AF",
  SM: "EU",
  SN: "AF",
  SO: "AF",
  SR: "SA",
  SS: "AF",
  ST: "AF",
  SV: "NA",
  SX: "NA",
  SY: "AS",
  SZ: "AF",
  TC: "NA",
  TD: "AF",
  TF: "AN",
  TG: "AF",
  TH: "AS",
  TJ: "AS",
  TK: "OC",
  TL: "OC",
  TM: "AS",
  TN: "AF",
  TO: "OC",
  TR: "AS",
  TT: "NA",
  TV: "OC",
  TW: "AS",
  TZ: "AF",
  UA: "EU",
  UG: "AF",
  UM: "OC",
  US: "NA",
  UY: "SA",
  UZ: "AS",
  VA: "EU",
  VC: "NA",
  VE: "SA",
  VG: "NA",
  VI: "NA",
  VN: "AS",
  VU: "OC",
  WF: "OC",
  WS: "OC",
  XK: "EU",
  YE: "AS",
  YT: "AF",
  ZA: "AF",
  ZM: "AF",
  ZW: "AF",
} as const;

const ContinentNames = {
  EU: "Europe",
  AS: "Asia",
  NA: "North America",
  SA: "South America",
  OC: "Oceania",
  AF: "Africa",
};

export function getContinentName(code: string): string {
  const continentCode =
    ContinentCodes[code.toUpperCase() as keyof typeof ContinentCodes];

  if (!continentCode) {
    throw new Error(`"${code}" is an invalid ISO country code`);
  }

  return ContinentNames[continentCode as keyof typeof ContinentNames];
}

export function getCountryFullName(code: string): string {
  return COUNTRIES[code.toUpperCase() as keyof typeof COUNTRIES];
}
