export const competitors = {
  bitly: {
    name: "Bitly",
    slug: "bitly",
    tagline: "The most popular URL shortener",
    description:
      "Bitly is the most well-known URL shortener, but its free plan has become extremely restrictive. See how iShortn compares.",
    freeLinks: "5/month",
    freeAnalytics: "30 days, basic clicks only",
    customDomains: "Paid only",
    qrCodes: "2/month on free",
    apiAccess: "Paid only",
    teamFeatures: "Enterprise only",
    passwordProtection: "Paid only",
    pricing: "Free, Core $35/mo, Growth $300/mo",
    whySwitch: [
      "Bitly's free plan only allows 5 links per month — iShortn gives you 30",
      "Bitly free links may show interstitial ad pages before redirecting",
      "Bitly charges $35/month for Core — iShortn Pro is just $5/month",
      "iShortn includes full analytics, QR codes, and password protection on all plans",
      "No API access on Bitly free — iShortn Pro includes full API for $5/month",
    ],
  },
  tinyurl: {
    name: "TinyURL",
    slug: "tinyurl",
    tagline: "The original URL shortener",
    description:
      "TinyURL was one of the first URL shorteners, but it lacks analytics and modern features. See how iShortn compares.",
    freeLinks: "Unlimited (no account needed)",
    freeAnalytics: "None",
    customDomains: "Paid only",
    qrCodes: "Paid only",
    apiAccess: "Paid only",
    teamFeatures: "None",
    passwordProtection: "None",
    pricing: "Free, Pro $9.99/mo, Bulk $99/mo",
    whySwitch: [
      "TinyURL offers zero analytics on the free plan — iShortn tracks every click with detailed data",
      "No QR codes, custom domains, or password protection on TinyURL free",
      "TinyURL free plan shows ads — iShortn is ad-free on all plans",
      "Even TinyURL Pro at $9.99/month only offers basic click counts — iShortn free gives you more",
      "iShortn includes AI-powered link safety scanning on all plans",
    ],
  },
  rebrandly: {
    name: "Rebrandly",
    slug: "rebrandly",
    tagline: "Branded link management platform",
    description:
      "Rebrandly focuses on branded links with a generous free tier for custom domains, but iShortn delivers more analytics at a lower price.",
    freeLinks: "500 total",
    freeAnalytics: "Basic click tracking",
    customDomains: "5 on free plan",
    qrCodes: "Watermarked on free",
    apiAccess: "Paid only",
    teamFeatures: "Paid only",
    passwordProtection: "Paid only",
    pricing: "Free, Essentials $13/mo, Professional $32/mo",
    whySwitch: [
      "Rebrandly free gives 500 total links — iShortn gives 30 new links every month, ongoing",
      "Rebrandly Essentials costs $13/month — iShortn Pro is just $5/month",
      "Rebrandly QR codes have watermarks on free — iShortn QR codes are clean on all plans",
      "iShortn includes geo-targeting and AI-powered security that Rebrandly charges extra for",
    ],
  },
  "short-io": {
    name: "Short.io",
    slug: "short-io",
    tagline: "White-label link shortener",
    description:
      "Short.io is a solid link shortener focused on custom domains, but iShortn offers a more complete feature set at a better price.",
    freeLinks: "1,000 total",
    freeAnalytics: "50,000 tracked clicks",
    customDomains: "Required (bring your own)",
    qrCodes: "Yes",
    apiAccess: "Yes (1,000 API links)",
    teamFeatures: "Paid only",
    passwordProtection: "Paid only",
    pricing: "Free, Pro $19/mo, Business $48/mo",
    whySwitch: [
      "Short.io requires you to bring your own domain even to get started — iShortn works instantly",
      "Short.io free gives 1,000 links total lifetime — iShortn gives fresh links every month",
      "Short.io Business plan is $48/month — iShortn Pro is just $5/month",
      "iShortn includes password protection and AI-powered phishing detection on all links",
    ],
  },
  dub: {
    name: "Dub.co",
    slug: "dub",
    tagline: "Open-source link management",
    description:
      "Dub.co is an open-source link management platform popular with developers. See how iShortn compares on features and pricing.",
    freeLinks: "25/month",
    freeAnalytics: "30-day retention",
    customDomains: "3 on free plan",
    qrCodes: "Yes",
    apiAccess: "Yes (limited)",
    teamFeatures: "Paid only",
    passwordProtection: "Paid only",
    pricing: "Free, Pro $24/mo, Business $59/mo",
    whySwitch: [
      "Dub Pro costs $24/month — iShortn Pro is just $5/month for similar features",
      "Dub free analytics only goes back 30 days — same as iShortn free, but iShortn Pro unlocks unlimited retention for $5 vs Dub's $24",
      "iShortn offers 30 free links/month vs Dub's 25",
      "iShortn includes password protection and geo-targeting on the Pro plan",
    ],
  },
} as const;

export type Competitor = (typeof competitors)[keyof typeof competitors];
