export const AUDIENCE_FEEDBACK_LABELS: Record<string, string> = {
  free: "Free",
  pro: "Pro",
  ultra: "Ultra",
  founder: "Founder",
  marketer: "Marketer",
  developer: "Developer",
  agency: "Agency",
  creator: "Creator",
  educator: "Educator",
  other: "Other",
  social_media: "Social media",
  marketing_campaigns: "Marketing campaigns",
  client_links: "Client links",
  product_links: "Product links",
  qr_codes: "QR codes",
  internal_sharing: "Internal sharing",
  "1_10": "1–10",
  "11_50": "11–50",
  "51_200": "51–200",
  "201_1000": "201–1,000",
  "1000_plus": "1,000+",
  search: "Search",
  social: "Social",
  friend_or_colleague: "Friend or colleague",
  community: "Community",
  directory: "Directory",
  ad: "Ad",
  none: "None",
  bitly: "Bitly",
  dub: "Dub",
  tinyurl: "TinyURL",
  rebrandly: "Rebrandly",
  shortio: "Short.io",
  custom_domains: "Custom domains",
  analytics: "Analytics",
  folders: "Folders",
  utm_templates: "UTM templates",
  geo_rules: "Geo rules",
  teams: "Teams",
  more_links: "More links",
  more_analytics: "More analytics",
  support_the_product: "Support the product",
};

export function formatAudienceFeedbackLabel(value: string | null | undefined): string {
  if (!value) return "—";
  return AUDIENCE_FEEDBACK_LABELS[value] ?? value;
}
