version: "3.8"

name: ishortn
services:
  database:
    image: mysql:latest
    container_name: ishortn_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ishortn_rewrite
      - MYSQL_USER=ishortn
      - MYSQL_PASSWORD=ishortn
    ports:
      - "3306:3306"
    volumes:
      - ishortndb:/var/lib/postgresql/data

  cache:
    image: redis:latest
    container_name: ishortn_cache
    ports:
      - "6379:6379"
    volumes:
      - ishortncache:/var/lib/redis/data

volumes:
  ishortndb:
  ishortncache:
