export const someKnownDesktopDevices = [
  // Sometimes, ua-parser-js doesn't detect the device type
  // correctly although it will detect the OS correctly.
  // So, we need to manually add some known desktop devices
  // here. This is not an exhaustive list.
  "AIX",
  "Amiga OS",
  "Arch",
  "BeOS",
  "CentOS",
  "Chromium OS",
  "Debian",
  "DragonFly",
  "Fedora",
  "FreeBSD",
  "Gentoo",
  "GNU",
  "Haiku",
  "Hurd",
  "Joli",
  "Linpus",
  "Linux",
  "Mac OS",
  "Mageia",
  "Mandriva",
  "MeeGo",
  "Minix",
  "Mint",
  "Morph OS",
  "NetBSD",
  "OpenBSD",
  "OpenVMS",
  "OS/2",
  "PCLinuxOS",
  "Plan9",
  "QNX",
  "RedHat",
  "RISC OS",
  "Series40",
  "Slackware",
  "Solaris",
  "SUSE",
  "Tizen",
  "Ubuntu",
  "UNIX",
  "VectorLinux",
  "WebOS",
  "Zenwalk",
];
